feat: allow custom package configuration file path
gatling/gatling-maven-plugin pull request #169
Opened 2024-04-17 12:38 UTC by tpetillot

Ref: HYB-596

2024-04-17 12:48 UTC, slandelle approved these changes

2024-04-17 16:46 UTC, Obero approved these changes

2024-04-17 16:46 UTC, Obero commented on src/main/java/io/gatling/mojo/EnterpriseDeployMojo.java
> +  @Parameter(property = "gatling.enterprise.packageConf")
Choose wisely :older_adult:

2024-04-18 09:47 UTC, Obero requested changes
Need to bump commons version

2024-04-18 09:54 UTC, Obero commented on src/main/java/io/gatling/mojo/EnterpriseDeployMojo.java
> +  @Parameter(property = "gatling.enterprise.packageConf")
packageDescriptorFilename

2024-04-18 10:13 UTC, Obero approved these changes
Upgrade done, including this PR content: https://github.com/gatling/gatling-maven-plugin/pull/168#pullrequestreview-2008184449

2024-04-18 10:13 UTC, merged