enable GitHub Actions CI
gatling/gatling-maven-plugin pull request #28
Opened 2021-01-31 23:05 UTC by sullis

2021-02-01 08:25 UTC, slandelle commented
@lsammoc WDYT?

2021-02-01 08:26 UTC, slandelle requested changes
If we switch to GH Actions, we should remove the Travis configuration.

2021-02-01 08:31 UTC, sullis commented
> If we switch to GH Actions, we should remove the Travis configuration.

Done.

2021-02-01 14:05 UTC, Isammoc requested changes

2021-02-01 14:05 UTC, Isammoc commented on .github/workflows/ci.yml
> +          ${{ runner.os }}-maven-
```suggestion
        key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          maven-${{ runner.os }}-
          maven-
```

2021-02-01 14:05 UTC, Isammoc commented on .github/workflows/ci.yml
> +      run: mvn --no-transfer-progress -B clean verify
```suggestion
      run: mvn --no-transfer-progress -B clean verify
    - name: Clean before caching
      run: find ~/.m2 -name "_remote.repositories" | xargs rm
```

2021-02-01 14:07 UTC, Isammoc commented
Thank you, @sullis!

Only minor changes and I think we will be good to go!

@slandelle One task I don't have to do myself ^^ :+1: 
The CLA?

2021-02-01 14:12 UTC, slandelle commented
@Isammoc CLA is good, @sullis has already signed it for another PR.

2021-02-07 18:10 UTC, sullis commented
Ready for review @slandelle  @Isammoc

2021-02-08 09:04 UTC, Isammoc approved these changes

2021-02-08 09:05 UTC, slandelle approved these changes

2021-02-08 09:06 UTC, merged

2021-02-08 09:06 UTC, slandelle commented
@sullis Thanks!