WIP: feat: delegate simulation class discovery to common package MISC-355
gatling/gatling-maven-plugin pull request #88
Opened 2022-03-31 06:48 UTC by bastien-gatling

Motivation:
gatling-enterprise-plugin-common now look for simulation classes.

Modifications:
* Delegate simulations discovery to commons library
* Handle introduced exceptions
* Take advantage of common interface between batch and interactive
  enterprise plugin

Result:
If there is no simulation classes, error is returned during plugin execution instead of on cloud.

Ref: MISC-355

2022-03-31 06:49 UTC, bastien-gatling commented on pom.xml
> +        <gatling-enterprise-plugin-commons.version>1.0.3-SNAPSHOT</gatling-enterprise-plugin-commons.version>
Waiting for the release version when PR on common is merged.

2022-03-31 08:57 UTC, Isammoc approved these changes

2022-04-01 14:49 UTC, tpetillot commented on src/main/java/io/gatling/mojo/EnterpriseStartMojo.java
> +      getLog().info("Creating and starting simulation (batch mode)...");
IMO, log is not needed (log that are not about configuration should be in commons).
But isInteractiveMode lead to batch mode log ?

2022-04-01 14:51 UTC, tpetillot requested changes
Simulation class needed in batch mode upload and start

2022-04-01 16:03 UTC, bastien-gatling commented on src/main/java/io/gatling/mojo/EnterpriseStartMojo.java
> +              UUID.fromString(simulationId), simulationSystemProperties, null, file)
good catch, thanks !

2022-04-04 08:43 UTC, tpetillot approved these changes

2022-04-04 09:07 UTC, merged